/*
 * ButtonVariables.h
 *
 * Created: 02/11/2023 20:57:46
 *  Author: josefe
 */ 


#ifndef BUTTONVARIABLES_H_
#define BUTTONVARIABLES_H_

#define BUTTON_NO_PRESS 0
#define BUTTON_SHORT_PRESS 1
#define BUTTON_LONG_PRESS 2

#define PULSE_ONGOING 1
#define PULSE_IDLE 0

#define EEPROM_ADDRESS 50

#define BUTTON_FSM_DELAY_MILLIS 50
#define PULSE_FSM_DELAY_MILLIS 1

#define BUTTON_DEBOUNCE_DURATION_MILLIS 50
#define BUTTON_LONG_PRESS_DURATION_MILLIS 4000

#define PULSE_DURATION_TIME_MILLIS 250
#define PULSE_SETTLING_TIME_MILLIS 200

#define LED_LINE_DEBOUNCE_MILLIS 10

enum ButtonFSMStates
{
	BUTTON_IDLE,
	BUTTON_PRESSED,
	BUTTON_PRESSED_DEBOUNCE,
	BUTTON_RELEASE_DEBOUNCE,
	BUTTON_LONG_PRESS_RELEASE_PENDING,
	BUTTON_LONG_PRESS_RELEASE_PENDING_DEBOUNCE,	
	BUTTON_DEPRESSED
};

#endif /* BUTTONVARIABLES_H_ */